# 提权操作
ansible_become: true
command_warnings: false

redis_download_url: https://oss.saas.hand-china.com/middleware/redis-5.0.12.tar.gz
redis_tarball_path: "/tmp/{{ redis_download_url.split('/')[-1] }}"
redis_code_path: "{{ redis_tarball_path.split('.tar.gz')[0] }}"

redis_sentinel_config:
  port: 26379
  logfile: /var/log/redis/sentinel.log

{{base-config}}